Verificacion de la cuenta de este o no creada en firebase
BrightCoders-Institute/BCDIC22-RN-reservacion-vuelos-team1 pull request #16
Opened 2023-01-27 00:49 UTC by Matarratas777

Co-authored-by: Gaddiel Patiño <GaddPat0609@users.noreply.github.com>
Co-authored-by: EliasCode79 <EliasCode79@users.noreply.github.com>

# Description

check if the account is created in firebase and if it is shown in the console and if not, it is created in addition to being able to enter the session if the account is yours

Examples:
![Imagen de WhatsApp 2023-01-26 a las 18 40 40](https://user-images.githubusercontent.com/63115824/214982482-7ef0a166-87ca-4ec9-93e1-c0ef0430bec6.jpg)

![Imagen de WhatsApp 2023-01-26 a las 18 41 48](https://user-images.githubusercontent.com/63115824/214982505-1e36f979-8ce8-40bd-9d7f-a60a3b650098.jpg)

![Imagen de WhatsApp 2023-01-26 a las 18 43 18](https://user-images.githubusercontent.com/63115824/214982525-b00925d6-f017-4366-8774-45287011527f.jpg)

2023-01-27 00:51 UTC, Zuack55 approved these changes
Good job

2023-01-27 00:52 UTC, IvanGodinez21 approved these changes
LGTM 🤯

2023-01-27 00:55 UTC, HenrikhWolf approved these changes
LGTM 👍

2023-01-30 16:02 UTC, YilKanda requested changes

2023-01-30 16:02 UTC, YilKanda commented on src/views/pantallaRegis/pantallaRegis.js
> +        console.log(errorCode, errorMessage)
On GitHub, you should not leave debugging code.

Instead you can use an Alert.alert(), indicating some message like: "User not logged in"

2023-01-30 16:02 UTC, YilKanda commented on src/views/pantallaRegis/pantallaRegis.js
> +        console.log(errorCode, errorMessage)
On GitHub, you should not leave debugging code.

Instead you can use an Alert.alert(), indicating some message like: "User not logged in"

2023-01-31 21:11 UTC, merged